// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { resolve } from 'path';
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

/**
 * Load environment variables from the appropriate .env file
 * This matches the logic in src/config/env.ts
 */
function getEnvFilePath(): string {
  const appEnv = process.env.APP_ENV || process.env.NODE_ENV || 'development';
  const envFile = appEnv === 'production' ? '.env.prod' : '.env.dev';
  return resolve(process.cwd(), envFile);
}

// Load environment variables
const envFilePath = getEnvFilePath();
config({ path: envFilePath });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
